export const API_ENDPOINTS = {
  AUTH: {
    CANDIDATE_LOGIN_OTP: '/auth/candidate/login/send-otp',
    CANDIDATE_REGISTER_OTP: '/auth/candidate/register/send-otp',
    VERIFY_OTP: '/auth/candidate/verify-otp',
    ME: '/auth/me',
    ADMIN_LOGIN: '/auth/admin/login',
    VERIFY_INVITATION: (token) => `/auth/invitation/verify/${token}`,
    ACCEPT_INVITATION: '/auth/invitation/accept',
  },
  ADMIN: {
    DASHBOARD_STATS: '/admin/dashboard-stats',
    ME: '/admin/me',
    ADMINS: '/admin/admins',
    ADMIN_DETAIL: (id) => `/admin/admins/${id}`,
    CANDIDATE_DETAIL: (id) => `/admin/candidates/${id}`,
  },
  ORGANIZATIONS: {
    LIST: '/admin/organizations',
    DETAILS: (id) => `/admin/organizations/${id}`,
    INVITATIONS: '/admin/invitations',
    INVITATION_DETAIL: (id) => `/admin/invitations/${id}`,
    VERIFICATIONS: '/admin/verifications',
    VERIFICATION_DETAIL: (id) => `/admin/verifications/${id}`,
    SUSPEND: (id) => `/admin/organizations/${id}/suspend`,
    REACTIVATE: (id) => `/admin/organizations/${id}/reactivate`,
  },
  JOBS: {
    LIST: '/admin/jobs',
    STATS: '/admin/jobs/stats',
    DETAILS: (id) => `/admin/jobs/${id}`,
    PIPELINE: (id) => `/admin/jobs/${id}/pipeline`,
    PIPELINE_STATS: (id) => `/admin/jobs/${id}/pipeline/stats`,
    APPLICATION_CHAT: (applicationId) => `/admin/jobs/applications/${applicationId}/chat`,
  },
  CANDIDATES: {
    LIST: '/admin/candidates',
    STATS: '/admin/candidates/stats',
    DETAILS: (id) => `/admin/candidates/${id}`,
    STATUS: (id) => `/admin/candidates/${id}/status`,
  },
  USERS: {
    LIST: '/admin/users',
    STATS: '/admin/users/stats',
    ORGANIZATIONS: '/admin/users/organisations',
    TOGGLE_STATUS: (id) => `/admin/users/${id}/toggle`,
  },
  ENTITIES: {
    ALL: '/admin/entities/all',
    BASE: '/admin/entities',
    DETAIL: (id) => `/admin/entities/${id}`,
  },
  HOSPITAL_JOIN_REQUESTS: {
    LIST: '/admin/access-requests',
    STATS: '/admin/hospital-join-requests/stats',
    DETAIL: (id) => `/admin/hospital-join-requests/${id}`,
  },
};
